channels:
- lcls-ii
- conda-forge
- defaults
- tidair-packages
- cogsci
dependencies:
- python=3.10
- setuptools
- cmake
- make
- gcc_linux-64
- gxx_linux-64
- numpy
- mpi4py
- cython
- matplotlib
- pytest
- mongodb
- pymongo
- curl
- mypy_extensions
- psmon
- h5py
- krtc
- roentdek
- htop
- asyncqt
- setproctitle
- networkfox
- pint
- pyfftw
- cogsci::pyqode.python
- pyzmq
- zeromq
- pyqt
- pyqtgraph
- epics-base
- readline
- dill
- flake8
- opencv
- scikit-learn
- numba
- pydot
- pygraphviz
- qtpy
- sympy
- pytest-qt
- pytest-asyncio
- qtconsole
- p4p
- libfabric
- libnl
- rapidjson
- jedi=0.17.2
- transitions
- ipython
- requests
- ipdb
- prometheus-cpp
- prometheus_client
- amityping
- mypy
- rogue
- bluesky
- ophyd
- lcls2_timetool
- cameralink-gateway
- epix
- posix_ipc
- sysv_ipc
- pyabel
- git-lfs
- git
- lcls2-pgp-pcie-apps
- caproto
- scikit-image
- scikit-beam
- pytables
- openmpi
- lcls2-epix-hr-pcie
- epix-hr-single-10k
- gdb
- holoviews
- panel
- aes-stream-drivers
- mpich
name: ana-nersc-4.4.10
