name: nersc-base-psana2

on:
  push:
    branches:
      - 'main'
      - 'refactor'
    paths:
      - 'docker/nersc/base/psana2/Dockerfile'
      - '.github/workflows/nersc-base-psana2.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docker/nersc/base/psana2/Dockerfile'
      - '.github/workflows/nersc-base-psana2.yaml'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install dependencies
        run: pip install pyyaml docker jinja2
      - name: build container
        run: docker build --build-arg inputtxt=env.txt --tag fpoitevi/nersc:base-psana2 docker/nersc/base/psana2
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_FRED_USERNAME }}
          password: ${{ secrets.DOCKERHUB_FRED_TOKEN }}
      - name: upload container
        run: docker push fpoitevi/nersc:base-psana2