name: s3df

on:
  push:
    tags:
      - 'build-s3df'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install dependencies
        run: pip install pyyaml docker jinja2
      - name: build container
        run: docker build --tag fpoitevi/s3df:latest docker/s3df
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_FRED_USERNAME }}
          password: ${{ secrets.DOCKERHUB_FRED_TOKEN }}
      - name: upload container
        run: docker push fpoitevi/s3df:latest